version: 2.1
description: Fauna Shell Tests

executors:
  core:
    resource_class: large
    docker:
      - image: cimg/node:16.20.1

      - image: fauna/faunadb
        name: core

    environment:
      FAUNA_SECRET: secret
      FAUNA_DOMAIN: core
      FAUNA_SCHEME: http
      FAUNA_PORT: 8443

commands:
  build_and_test:
    description: "Run fauna-shell tests"
    steps:
      - checkout

      - setup_remote_docker:
          version: 24.0
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Wait FaunaDB init
          command: |
            while ! $(curl --output /dev/null --silent --fail --max-time 1 http://core:8443/ping); do sleep 1; done

      - run:
          name: Run Tests
          command: yarn test

jobs:
  fauna-shell-tests:
    executor:
      name: core
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - fauna-shell-tests:
          context: faunadb-drivers
