version: 2.1
description: Fauna Shell Tests

executors:
  core:
    resource_class: large
    docker:
      - image: cimg/node:18.20

    environment:
      FAUNA_SECRET: secret
      FAUNA_DOMAIN: core
      FAUNA_SCHEME: http
      FAUNA_PORT: 8443

commands:
  build_and_test:
    description: "Run fauna-shell tests"
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Run Tests
          command: |
            export FAUNA_SECRET=fn1234
            export FAUNA_DOMAIN=db.fauna.com
            export FAUNA_SCHEME=https
            export FAUNA_PORT=443
            export DEBUG=oclif-test
            yarn test

      - store_artifacts:
          path: coverage

jobs:
  fauna-shell-tests:
    executor:
      name: core
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - fauna-shell-tests:
          context: faunadb-drivers
