---
resources:
  - name: fauna-shell-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-shell.git
      branch: 1.1.1

jobs:
  - name: test
    serial: true
    plan:
      - get: fauna-shell-repository
        trigger: true
      - task: integration-tests
        file: fauna-shell-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_SECRET: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))
      - task: schema-tests
        file: fauna-shell-repository/concourse/tasks/schema-tests.yml
        params:
          FAUNA_SECRET: ((cli-test-secret))

  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-shell-repository
        passed: [test]
      - task: publish
        file: fauna-shell-repository/concourse/tasks/publish.yml
        params:
          NPM_TOKEN: ((npm_token))
