---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: shared-concourse-dind
    aws_access_key_id: ((prod-images-aws-access-key-id))
    aws_secret_access_key: ((prod-images-aws-secret-key))
    aws_region: us-east-2

params:
  FAUNA_SECRET:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:

inputs:
  - name: fauna-shell-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceux
    - |
      # start containers
      docker-compose -f fauna-shell-repository/concourse/tasks/integration.yml run tests
      # stop and remove containers
      docker-compose -f fauna-shell-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
