---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: node
    tag: 16.14.2-alpine3.14

params:
  NPM_TOKEN:

inputs:
  - name: fauna-shell-repository

run:
  path: ./fauna-shell-repository/concourse/scripts/publish.sh
