name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Tests
        uses: borales/actions-yarn@v4
        env:
          FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}
          FAUNA_DOMAIN: ${{ secrets.FAUNA_DOMAIN }}
          FAUNA_SCHEME: ${{ secrets.FAUNA_SCHEME }}
          FAUNA_PORT: ${{ secrets.FAUNA_PORT }}
        with:
          cmd: test
