name: Set JIRA ticket to DONE

on:
  issues:
    types: [closed, deleted]

jobs:
  set_done_for_closed_issued:
    name: Set JIRA ticket to DONE
    runs-on: ubuntu-latest
    uses: ./.github/workflows/jira-login.yml
    steps:
      - name: Find comment with ticket number
        uses: peter-evans/find-comment@v1
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Internal ticket number is FE-

      - name: Get ticket number
        id: ticket
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ steps.comment.outputs.comment-body }}

      - name: Close
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.ticket.outputs.issue }}
          transition: 'DONE'
