name: Create JIRA ticket for GH pull request

on:
  pull_request:
    types: [opened]

jobs:
  create_ticket_from_pr:
    name: Create ticket from pr
    runs-on: ubuntu-latest
    uses: ./jira-login.yml
    steps:
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: FE
          issuetype: Task
          summary: PR \#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}
          description: ${{ github.event.pull_request.html_url }}
          fields: '{"labels": ["github", "pr", "dx-ops"], "components": [{ "name": "Fauna Shell" }]}'

      - name: Complete
        if: ${{ steps.create.outputs.issue }}
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
