name: Create JIRA ticket for GH issue

on:
  issues:
    types: [opened]

jobs:
  create_ticket_from_issue:
    name: Create ticket from issue
    runs-on: ubuntu-latest
    uses: ./.github/workflows/jira-login.yml
    steps:
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: FE
          issuetype: Bug
          summary: GITHUB ISSUE \#${{ github.event.issue.number }} ${{ github.event.issue.title }}
          description: ${{ github.event.issue.html_url }}
          fields: '{"labels": ["github", "issue", "dx-ops"], "components": [{ "name": "Fauna Shell" }]}'

      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Internal ticket number is ${{ steps.create.outputs.issue }}

      - name: Complete
        if: ${{ steps.create.outputs.issue }}
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
